name: Rebase Pull Request

on:
  check_run:


env:
  workflow_name: "Say Hello Workflow"

jobs:
  main:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Echo
        run: echo ${{github.event.check_run.name}}

      - name: automatic rebase
        uses: cirrus-actions/rebase@1.5
        if: ${{ github.event.check_run.name == $workflow_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}