name: Rebase Pull Request

on:
  check_run:
    types: [completed]


env:
  workflow_name: "ci/circleci: Say Hello"

jobs:
  main:
    if: ${{ github.event.check_run.name == $workflow_name }}
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: automatic rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}